import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/Navbar";
import { inter } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "MovieQ",
  description: "Generated by create next app.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-inter dark antialiased",
          inter.variable
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
